HeatTemplateFormatVersion: 2012-12-12
Description: A bare bone instance using any NeCTAR image. This is used for defining essential parts of a HEAT CFN template.
Parameters:
  ImageId:
    Description: >
      Any NeCTAR image name or ID. NeCTAR reuse image name when 
      there is an update of an image. So if you want a specific 
      image, use ID. NeCTAR does not keep all IDs of an image, so 
      you might have to keep a list yourself.
    Type: String
    Default: 'NeCTAR CentOS 6.5 x86_64' 
  InstanceType: 
    Description: OpenStack instance type
    Type: String
    ConstraintDescription: must be a valid OpenStack instance type.
    AllowedValues: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
    Default: m1.small
  KeyName: 
    Description: Name of an existing OpenStack KeyPair to enable SSH access to the instances.
    Type: String
    ConstraintDescription: can contain only alphanumeric characters, dashes and underscores.
    AllowedPattern: '[-_ a-zA-Z0-9]*'
    MaxLength: 64
    MinLength: 1

Resources:
  SecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
      - {IpProtocol: tcp, FromPort: '22', ToPort: '22', CidrIp: 0.0.0.0/0}
  Barebone:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [{Ref: SecurityGroups}]

Outputs:
  Instance_IP:
    Description: The IP address of the deployed instance. SSH in with your key.
    Value: {'Fn::GetAtt': [Barebone, PublicIp]}
