HeatTemplateFormatVersion: '2012-12-12'

Description: A snippet of using configSets to control what to do when instance is being created. The example works with Fedora images only.
 
Parameters:
  ServerType:
    Type: String
    ConstraintDescription: must be one of pre-defined value of configSets.
    AllowedValues: [simple, with_php]
    Default: with_php

Resources:
  Webserver:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init:
        configSets:
          simple: [ httpd_only ]
          with_php: [ "lan_php", {"ConfigSet": "simple"} ] 
        lan_php: 
          packages: 
            yum: 
              php: []
          files:
            /var/www/html/index.php:
              content: |
                <?php
                phpinfo();
                phpinfo(INFO_MODULES);
                ?>
        httpd_only: 
          packages: 
            yum: 
              httpd: []
          services:
            systemd:
              httpd: {enabled: true, ensureRunning: true}

    Properties: 
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [{Ref: SecurityGroups}]
      UserData: 
        Fn::Base64: 
           Fn::Replace:
            - AWS::StackName: {Ref: 'AWS::StackName'}
              ServerType: {Ref: ServerType}
            - |
                #!/bin/bash -v
                yum update -y
                /usr/bin/cfn-init -s AWS::StackName -r Webserver -c ServerType
