HeatTemplateFormatVersion: 2012-12-12

Description: XFCE decstop server using x2go using Fedroa image. 
 
Parameters:
  ImageId:
    Description: Any NeCTAR Fedora image ID. Check default ID if failed to create.
    Type: String
    Default: 249167f4-3d45-402a-9362-557c23628352
  InstanceType: 
    Description: OpenStack instance type
    Type: String
    ConstraintDescription: must be a valid OpenStack instance type.
    AllowedValues: [m1.tiny, m1.small]
    Default: m1.small
  KeyName: 
    Description: Name of an existing OpenStack KeyPair to enable SSH access to the instances.
    Type: String
    ConstraintDescription: can contain only alphanumeric characters, dashes and underscores.
    AllowedPattern: '[-_ a-zA-Z0-9]*'
    MaxLength: 64
    MinLength: 1

Resources:
  FXFCE:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          packages: 
            yum: 
              x2goserver : [] 
              firefox    : [] 
    Properties: 
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [ default ]
      UserData: 
        Fn::Base64: 
           Fn::Replace:
            - AWS::StackName: {Ref: 'AWS::StackName'}
            - |
                #!/bin/bash -v
                yum update -y
                /usr/bin/cfn-init -s AWS::StackName -r FXFCE 
                yum -y install @xfce

Outputs:
  Instance_IP:
    Description: The IP address of the deployed instance. SSH in with your key.
    Value: {'Fn::GetAtt': [FXFCE, PublicIp]}
