HeatTemplateFormatVersion: '2012-12-12'

Description: >
 A bare bone instance using any NeCTAR Fedora image supports 
 cfn-tools. This is used for defining essential parts of a HEAT CFN 
 template with packages and services. Useful for trying things are 
 new. 
 
Parameters:
  ImageId:
    Description: Any NeCTAR Fedora image ID. Check default ID if failed to create.
    Type: String
    Default: 249167f4-3d45-402a-9362-557c23628352
  InstanceType: 
    Description: Opebnstack instance type
    Type: String
    ConstraintDescription: must be a valid nova instance type.
    AllowedValues: ['m1.small', 'm1.medium', 'm1.large']
    Default: m1.small
  KeyName: 
    Description: Name of an existing OpenStack KeyPair to enable SSH access to the instances.
    Type: String
    ConstraintDescription: can contain only alphanumeric characters, spaces, dashes and underscores.
    AllowedPattern: '[-_ a-zA-Z0-9]*'
    MaxLength: 64
    MinLength: 1
  InstanceType:
    Type: String
    ConstraintDescription: must be a valid Openstack instance type.
    AllowedValues: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
    Default: m1.small

Resources:
  SecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, HTTP access
      SecurityGroupIngress:
      - {IpProtocol: tcp, FromPort: '22', ToPort: '22', CidrIp: 0.0.0.0/0}
      - {IpProtocol: tcp, FromPort: '80', ToPort: '80', CidrIp: 0.0.0.0/0}
  Barebone:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          packages: 
            yum: 
              httpd: []
          services:
            systemd:
              httpd: {enabled: true, ensureRunning: true}
    Properties: 
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [{Ref: SecurityGroups}]
      UserData: 
        Fn::Base64: 
           Fn::Replace:
            - AWS::StackName: {Ref: 'AWS::StackName'}
            - |
                #!/bin/bash -v
                yum update -y
                /usr/bin/cfn-init -s AWS::StackName -r Barebone 

Outputs:
  Instance_IP:
    Description: The IP address of the deployed instance. SSH in with your key.
    Value: {'Fn::GetAtt': [Barebone, PublicIp]}
  Server_URL:
    Description: URL of this instance.
    Value: 
      Fn::Join: 
        - ''
        -
          - http://
          - {'Fn::GetAtt': [Barebone, PublicIp]}
