HeatTemplateFormatVersion: 2012-12-12

Description: >
  RStudio IDE: the premier integrated development environment for 
  R runs on XFCE4 desktop. More info: http://www.rstudio.com/.
  You connect RStudio IDE using X2Go client. It can be downloaded at:
  http://wiki.x2go.org/doku.php/doc:installation:x2goclient. Try RStudio's
  daily builds for the latest otherwise pick up a stable release. The security
  group is default: only SSH is allowed. The desktop is Fedora spin of XFCE4.
Parameters:
  ImageId:
    Description: Any NeCTAR image ID. The image has to have cfn-tools intalled. Defaut is NeCTAR Fedora 20.
    Type: String
    Default: 249167f4-3d45-402a-9362-557c23628352
  InstanceType: 
    Description: OpenStack instance type
    Type: String
    ConstraintDescription: must be a valid OpenStack instance type.
    AllowedValues: [m1.small, m1.medium]
    Default: m1.small
  KeyName: 
    Description: Name of an existing OpenStack KeyPair to enable SSH access to the instances.
    Type: String
    ConstraintDescription: can contain only alphanumeric characters, dashes and underscores.
    AllowedPattern: '[-_ a-zA-Z0-9]*'
    MaxLength: 64
    MinLength: 1
  SSHLocation:
    Description: The IP address range that can be used to SSH to the instances. By default, any one can access. 
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: '0.0.0.0/0'
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  AvailabilityZone:
    Description: Where to host the instance. If you want to access volume storage, this has to be the zone where the volume is.
    Type: String
    AllowedValues: [melbourne, melbourne-qh2, monash, sa, NCI]
    Default: NCI
  Build:
    Description: >
     Choose what type of build: can either be stable release or daily build.
     Note: since May 2014 there is no release supports Fedora 20 with R 3.1.0.
     So on such systems, choose daily build.
    Type: String
    AllowedValues: [Daily, Stable]
    Default: Daily
  Version:
    Description: >
     The version of RStudio. Check on RStudio's website to match with release or build. 
     The default value is the latest stable release version.
     Note: on May 30, 2014 there is no release supports Fedora 20. So we 
     get 0.98.872 from daily builds server at the time of writing.
    Type: String
    AllowedPattern: '\d+\.\d+\.\d+'

Resources:
  SecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, HTTP access
      SecurityGroupIngress:
      - {IpProtocol: tcp, FromPort: '22', ToPort : '22', CidrIp : { Ref : SSHLocation}}
  RStudio:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          packages: 
            yum: 
              x2goserver           : [] 
              firefox              : []
              xorg-x11-fonts-Type1 : []
              R                    : [] 
              mousepad             : []
               
    Properties: 
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [{Ref: SecurityGroups}]
      AvailabilityZone: {Ref: AvailabilityZone}
      UserData: 
        Fn::Base64: 
           Fn::Replace:
            - AWS::StackName: {Ref: 'AWS::StackName'}
              repourl: { "Fn::Select" : [ {Ref: Build}, {Daily: 'https://s3.amazonaws.com/rstudio-dailybuilds' , Stable: 'http://download1.rstudio.org' } ] }
              version: {Ref: Version} 
            - |
                #!/bin/bash -v
                yum -y update
                yum -y install @xfce # group installation
                cfn-init -s AWS::StackName -r RStudio
                yum -y install --nogpgcheck repourl/rstudio-version-x86_64.rpm
                  
Outputs:
  Instance_IP:
    Description: Use X2Go client to access remote R IDE. User name is ec2-user.
    Value: {'Fn::GetAtt': [RStudio, PublicIp]}
