HeatTemplateFormatVersion: 2012-12-12

Description: >
  RStudio Server: the premier integrated development environment for 
  R runs over the web. More info: http://www.rstudio.com/
Parameters:
## No NeCTAR ubuntu image has cfn-tools supprts
  ImageId:
    Description: Any NeCTAR image ID. The image has to have cfn-tools intalled. Defaut is CentOS 6.5.
    Type: String
    Default: 96761a90-635b-4718-8deb-f4ff57632db4
  InstanceType: 
    Description: OpenStack instance type
    Type: String
    ConstraintDescription: must be a valid OpenStack instance type.
    AllowedValues: [m1.small, m1.medium, m1.large]
    Default: m1.small
  KeyName: 
    Description: Name of an existing OpenStack KeyPair to enable SSH access to the instances.
    Type: String
    ConstraintDescription: can contain only alphanumeric characters, dashes and underscores.
    AllowedPattern: '[-_ a-zA-Z0-9]*'
    MaxLength: 64
    MinLength: 1
  Distro: 
    Description: Name of Linux distribution of the image. Pick up one you are familiar with in case you want to manage the server. Has to match to the image of choice.
    Type: String
    AllowedValues: [CentOS, Ubuntu]
    Default: CentOS
  AvailabilityZone:
    Description: Where to host the instance. If you want to access volume storage, this has to be the zone where the volume is.
    Type: String
    AllowedValues: [melbourne, melbourne-qh2, monash, sa, NCI]
    Default: sa
  Build:
    Description: >
     Choose what type of build: can either be stable release or daily build.
     Note: since May 2014 there is no release supports Fedora 20 with R 3.1.0.
     So on such systems, choose daily build.
    Type: String
    AllowedValues: [Daily, Stable]
    Default: Daily
  Version:
    Description: >
     The version of RStudio. 
     Note: since R 3.1.0 release in EPEL in May, 2014 there is no stable release supports CentOS.
     So this version will be for daily build if CentOS server is chosen. Default is 0.98.894. Other
     see http://www.rstudio.com/ide/download/preview
    Type: String
    MinLength: 4
    AllowedPattern: '\d+\.\d+\.\d+'
    ConstraintDescription: must be a valid RStudio version. Check on RStudio's website.
  DefaultUser:
    Description: The default login of RStudio. Has no privilege and not allowed to SSH into server.
    Type: String
    Default: studiomaster
  UserPasswd:
    Description: The password of the default login.
    Type: String
    NoEcho: true
  SSHLocation:
    Description: The IP address range that can be used to SSH to the instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: '0.0.0.0/0'
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  ClientLocation:
    Description: The IP address range that can be used to access RStudio server
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: '0.0.0.0/0'
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}\/[0-9]{1,2}$'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  SecurityGroups:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, HTTP access
      SecurityGroupIngress:
      - {IpProtocol: tcp, FromPort: '22', ToPort : '22', CidrIp : { Ref : SSHLocation}}
      - {IpProtocol: tcp, FromPort: '80', ToPort: '80', CidrIp: { Ref : SSHLocation}}
  RStudio:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        configSets:
          centos: [ centos ]
          ubuntu: [ ubuntu ] 
        centos: 
          packages: 
            yum: 
              R  : [] 
        ubuntu: 
          packages: 
            apt:
              r-base     : []
              gdebi-core : []
              libapparmor1 : []
              
    Properties: 
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [{Ref: SecurityGroups}]
      AvailabilityZone: {Ref: AvailabilityZone}
      UserData: 
        Fn::Base64: 
           Fn::Replace:
            - AWS::StackName: {Ref: 'AWS::StackName'}
              config: { "Fn::Select" : [ {Ref: Distro}, {CentOS: centos, Ubuntu: ubuntu} ] }
              repourl: { "Fn::Select" : [ {Ref: Build}, {Daily: 'https://s3.amazonaws.com/rstudio-dailybuilds' , Stable: 'http://download2.rstudio.org' } ] }
              version: {Ref: Version} 
              default_user: {Ref: DefaultUser} 
              userpass: {Ref: UserPasswd} 
            - |
                #!/bin/bash -v
                if [ config == 'ubuntu' ]; then
                  apt-get update
                  NO_LOGIN='/usr/sbin/nologin'
                else
                  yum -y update
                  NO_LOGIN='/sbin/nologin'
                fi
                cfn-init -s AWS::StackName -r RStudio -c config
                cd /tmp
                if [ config == 'centos' ]; then
                  yum -y install --nogpgcheck repourl/rstudio-server-version-x86_64.rpm
                else
                  wget repourl/rstudio-server-version-amd64.deb
                  gdebi -n rstudio-server-version-amd64.deb  
                fi
                echo www-port=80 >> /etc/rstudio/rserver.conf
                rstudio-server restart
                useradd -s $NO_LOGIN -d /home/default_user -m default_user
                echo default_user:userpass | chpasswd
                
Outputs:
  RStudio_URL:
    Description: Access RStudio just created at
    Value: 
      Fn::Join: 
        - ''
        -
          - http://
          - {'Fn::GetAtt': [RStudio, PublicIp]}
