HeatTemplateFormatVersion: 2012-12-12

Description: >
  XFCE desktop server using x2go on any cfn-tools enabled image. In 
  May 2014, ECDSA is not implemented in libssh2, therefore if in 
  known_hosts there is an entry of ECDSA fingerprint, x2go client 
  will fail to connect.
Parameters:
## No NeCTAR ubuntu image has cfn-tools supprts
  ImageId:
    Description: Any NeCTAR image ID. The image has to have cfn-tools intalled. Defaut is NeCTAR Fedora 20.
    Type: String
    Default: 249167f4-3d45-402a-9362-557c23628352
  InstanceType: 
    Description: OpenStack instance type
    Type: String
    ConstraintDescription: must be a valid OpenStack instance type.
    AllowedValues: [m1.small, m1.medium]
    Default: m1.small
  KeyName: 
    Description: Name of an existing OpenStack KeyPair to enable SSH access to the instances.
    Type: String
    ConstraintDescription: can contain only alphanumeric characters, dashes and underscores.
    AllowedPattern: '[-_ a-zA-Z0-9]*'
    MaxLength: 64
    MinLength: 1
  Distro: 
  #  It affects package management, service control and etc.  
    Description: Name of Linux distribution of the image.
    Type: String
    AllowedValues: [CentOS, Fedora, Ubuntu]
    Default: Fedora

Resources:
  XFCE:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        configSets:
          rh: [ rh ]
          centos: [ extra, rh ]
          ubuntu: [ ubuntu ] 
        rh: 
          packages: 
            yum: 
              x2goserver          : [] 
              x2goserver-xsession : [] 
              firefox             : []
        extra: 
          packages: 
            yum: 
              perl-DBD-SQLite     : [] 
        ubuntu: 
          packages: 
            apt:
              x2goserver          : [] 
              x2goserver-xsession : [] 
              xfce4               : []
              xfce4-goodies       : [] 
              xfce4-artwork       : []
              xubuntu-icon-theme  : []
              firefox             : [] 
    Properties: 
      ImageId: {Ref: ImageId}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      SecurityGroups: [ default ]
      UserData: 
        Fn::Base64: 
           Fn::Replace:
            - AWS::StackName: {Ref: 'AWS::StackName'}
              config: { "Fn::Select" : [ {Ref: Distro}, {Fedora: rh, CentOS: centos, Ubuntu: ubuntu} ] }
            - |
                #!/bin/bash -v
                if [ config == 'ubuntu' ]; then
                  apt-add-repository -y ppa:x2go/stable
                  apt-get update
                else
                  yum -y update
                  yum -y install @xfce # group installation
                fi
                cfn-init -s AWS::StackName -r XFCE -c config
                if [ config == 'centos' ]; then
                  service x2gocleansessions start
                fi  
Outputs:
  Instance_IP:
    Description: Use x2go client to access remote desktop or ssh in. But remember use x2go client first.
    Value: {'Fn::GetAtt': [XFCE, PublicIp]}
